import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { repoPath, filePath, fixCode, token } = await req.json();

    if (!repoPath || !filePath || !fixCode || !token) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const headers = {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github.v3+json",
      "X-GitHub-Api-Version": "2022-11-28",
    };

    // 1. Get default branch (main or master)
    const repoRes = await fetch(`https://api.github.com/repos/${repoPath}`, { headers });
    if (!repoRes.ok) throw new Error("Could not find repository. Check path and token.");
    const repoData = await repoRes.json();
    const defaultBranch = repoData.default_branch;

    // 2. Get the latest commit SHA of the default branch
    const refRes = await fetch(`https://api.github.com/repos/${repoPath}/git/ref/heads/${defaultBranch}`, { headers });
    if (!refRes.ok) throw new Error(`Could not fetch branch ${defaultBranch}`);
    const refData = await refRes.json();
    const baseSha = refData.object.sha;

    // 3. Create a new branch
    const branchName = `ai-fix-${Date.now()}`;
    const createBranchRes = await fetch(`https://api.github.com/repos/${repoPath}/git/refs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      })
    });
    if (!createBranchRes.ok) throw new Error("Failed to create new branch");

    // 4. Get the current file content to append to it
    const fileRes = await fetch(`https://api.github.com/repos/${repoPath}/contents/${filePath}?ref=${branchName}`, { headers });
    let newContent = fixCode;
    let fileSha = undefined;

    if (fileRes.ok) {
      const fileData = await fileRes.json();
      fileSha = fileData.sha;
      const decodedContent = Buffer.from(fileData.content, 'base64').toString('utf-8');
      
      // We append the AI fix to the bottom with a clear comment marker
      newContent = `${decodedContent}\n\n/* === AI AUDITOR FIX === */\n${fixCode}\n`;
    } else {
      // File doesn't exist, we will create it
      newContent = `/* === AI AUDITOR FIX === */\n${fixCode}\n`;
    }

    // 5. Update/Create the file in the new branch
    const updateRes = await fetch(`https://api.github.com/repos/${repoPath}/contents/${filePath}`, {
      method: 'PUT',
      headers,
      body: JSON.stringify({
        message: `🤖 AI Auditor: Optimization applied to ${filePath}`,
        content: Buffer.from(newContent).toString('base64'),
        sha: fileSha,
        branch: branchName
      })
    });
    if (!updateRes.ok) throw new Error("Failed to commit changes to the branch");

    // 6. Create the Pull Request
    const prRes = await fetch(`https://api.github.com/repos/${repoPath}/pulls`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        title: `🤖 AI Auditor Fix for ${filePath}`,
        body: `This PR was automatically generated by **AI Auditor**.\n\n### Fix Applied:\n\`\`\`javascript\n${fixCode}\n\`\`\`\n\n*Note: The code was appended to the file. Please review and move it to the correct location.*`,
        head: branchName,
        base: defaultBranch
      })
    });
    
    if (!prRes.ok) throw new Error("Failed to create Pull Request");
    const prData = await prRes.json();

    return NextResponse.json({ url: prData.html_url }, { status: 200 });

  } catch (error: any) {
    console.error("GitHub API Error:", error);
    return NextResponse.json({ error: error.message || "Failed to create PR" }, { status: 500 });
  }
}
